#!/bin/bash

. ~warehouse/.bash_profile > /dev/null 2>&1
echo "`date` `basename $0` $1 Started..."

MYENV=$1 

LOGFILE="/tmp/$MYENV`basename $0`.out"
LOCKFILE="/tmp/$MYENV`basename $0`.LOCK"


rm -f /home/warehouse/files/csv/keywords/$MYENV/outputKeyword*.csv

~/jq -r '.Response.Result[] | "\(.CreatedAt)\t\(.Id)\t\(.Keyword)\t\(.KeywordDevice)\t\(.KeywordLocation)\t\(.KeywordMarket)\t\(.KeywordRanking.Bing.Rank)\t\(.KeywordRanking.Bing.Url)\t\(.KeywordRanking.date)\t\(.KeywordRanking.Google.BaseRank)\t\(.KeywordRanking.Google.Rank)\t\(.KeywordRanking.Google.Url)\t\(.KeywordRanking.Yahoo.Rank)\t\(.KeywordRanking.Yahoo.Url)\t\(.KeywordStats.AdvertiserCompetition)\t\(.KeywordStats.CPC)\t\(.KeywordStats.GlobalSearchVolume)\t\(.KeywordStats.LocalSearchTrendsByMonth.Apr)\t\(.KeywordStats.LocalSearchTrendsByMonth.Aug)\t\(.KeywordStats.LocalSearchTrendsByMonth.Dec)\t\(.KeywordStats.LocalSearchTrendsByMonth.Feb)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jan)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jul)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jun)\t\(.KeywordStats.LocalSearchTrendsByMonth.Mar)\t\(.KeywordStats.LocalSearchTrendsByMonth.May)\t\(.KeywordStats.LocalSearchTrendsByMonth.Nov)\t\(.KeywordStats.LocalSearchTrendsByMonth.Oct)\t\(.KeywordStats.LocalSearchTrendsByMonth.Sep)\t\(.KeywordStats.RegionalSearchVolume)\t\(.KeywordTags)\t\(.RequestUrl)"' /home/warehouse/files/keywordList/$MYENV/keywordList0.json >> /home/warehouse/files/csv/keywords/$MYENV/outputKeyword0.csv 
~/jq -r '.Response.Result[] | "\(.CreatedAt)\t\(.Id)\t\(.Keyword)\t\(.KeywordDevice)\t\(.KeywordLocation)\t\(.KeywordMarket)\t\(.KeywordRanking.Bing.Rank)\t\(.KeywordRanking.Bing.Url)\t\(.KeywordRanking.date)\t\(.KeywordRanking.Google.BaseRank)\t\(.KeywordRanking.Google.Rank)\t\(.KeywordRanking.Google.Url)\t\(.KeywordRanking.Yahoo.Rank)\t\(.KeywordRanking.Yahoo.Url)\t\(.KeywordStats.AdvertiserCompetition)\t\(.KeywordStats.CPC)\t\(.KeywordStats.GlobalSearchVolume)\t\(.KeywordStats.LocalSearchTrendsByMonth.Apr)\t\(.KeywordStats.LocalSearchTrendsByMonth.Aug)\t\(.KeywordStats.LocalSearchTrendsByMonth.Dec)\t\(.KeywordStats.LocalSearchTrendsByMonth.Feb)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jan)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jul)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jun)\t\(.KeywordStats.LocalSearchTrendsByMonth.Mar)\t\(.KeywordStats.LocalSearchTrendsByMonth.May)\t\(.KeywordStats.LocalSearchTrendsByMonth.Nov)\t\(.KeywordStats.LocalSearchTrendsByMonth.Oct)\t\(.KeywordStats.LocalSearchTrendsByMonth.Sep)\t\(.KeywordStats.RegionalSearchVolume)\t\(.KeywordTags)\t\(.RequestUrl)"' /home/warehouse/files/keywordList/$MYENV/keywordList5000.json >> /home/warehouse/files/csv/keywords/$MYENV/outputKeyword5000.csv 
~/jq -r '.Response.Result[] | "\(.CreatedAt)\t\(.Id)\t\(.Keyword)\t\(.KeywordDevice)\t\(.KeywordLocation)\t\(.KeywordMarket)\t\(.KeywordRanking.Bing.Rank)\t\(.KeywordRanking.Bing.Url)\t\(.KeywordRanking.date)\t\(.KeywordRanking.Google.BaseRank)\t\(.KeywordRanking.Google.Rank)\t\(.KeywordRanking.Google.Url)\t\(.KeywordRanking.Yahoo.Rank)\t\(.KeywordRanking.Yahoo.Url)\t\(.KeywordStats.AdvertiserCompetition)\t\(.KeywordStats.CPC)\t\(.KeywordStats.GlobalSearchVolume)\t\(.KeywordStats.LocalSearchTrendsByMonth.Apr)\t\(.KeywordStats.LocalSearchTrendsByMonth.Aug)\t\(.KeywordStats.LocalSearchTrendsByMonth.Dec)\t\(.KeywordStats.LocalSearchTrendsByMonth.Feb)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jan)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jul)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jun)\t\(.KeywordStats.LocalSearchTrendsByMonth.Mar)\t\(.KeywordStats.LocalSearchTrendsByMonth.May)\t\(.KeywordStats.LocalSearchTrendsByMonth.Nov)\t\(.KeywordStats.LocalSearchTrendsByMonth.Oct)\t\(.KeywordStats.LocalSearchTrendsByMonth.Sep)\t\(.KeywordStats.RegionalSearchVolume)\t\(.KeywordTags)\t\(.RequestUrl)"' /home/warehouse/files/keywordList/$MYENV/keywordList10000.json >> /home/warehouse/files/csv/keywords/$MYENV/outputKeyword10000.csv
~/jq -r '.Response.Result[] | "\(.CreatedAt)\t\(.Id)\t\(.Keyword)\t\(.KeywordDevice)\t\(.KeywordLocation)\t\(.KeywordMarket)\t\(.KeywordRanking.Bing.Rank)\t\(.KeywordRanking.Bing.Url)\t\(.KeywordRanking.date)\t\(.KeywordRanking.Google.BaseRank)\t\(.KeywordRanking.Google.Rank)\t\(.KeywordRanking.Google.Url)\t\(.KeywordRanking.Yahoo.Rank)\t\(.KeywordRanking.Yahoo.Url)\t\(.KeywordStats.AdvertiserCompetition)\t\(.KeywordStats.CPC)\t\(.KeywordStats.GlobalSearchVolume)\t\(.KeywordStats.LocalSearchTrendsByMonth.Apr)\t\(.KeywordStats.LocalSearchTrendsByMonth.Aug)\t\(.KeywordStats.LocalSearchTrendsByMonth.Dec)\t\(.KeywordStats.LocalSearchTrendsByMonth.Feb)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jan)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jul)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jun)\t\(.KeywordStats.LocalSearchTrendsByMonth.Mar)\t\(.KeywordStats.LocalSearchTrendsByMonth.May)\t\(.KeywordStats.LocalSearchTrendsByMonth.Nov)\t\(.KeywordStats.LocalSearchTrendsByMonth.Oct)\t\(.KeywordStats.LocalSearchTrendsByMonth.Sep)\t\(.KeywordStats.RegionalSearchVolume)\t\(.KeywordTags)\t\(.RequestUrl)"' /home/warehouse/files/keywordList/$MYENV/keywordList15000.json >> /home/warehouse/files/csv/keywords/$MYENV/outputKeyword15000.csv 
~/jq -r '.Response.Result[] | "\(.CreatedAt)\t\(.Id)\t\(.Keyword)\t\(.KeywordDevice)\t\(.KeywordLocation)\t\(.KeywordMarket)\t\(.KeywordRanking.Bing.Rank)\t\(.KeywordRanking.Bing.Url)\t\(.KeywordRanking.date)\t\(.KeywordRanking.Google.BaseRank)\t\(.KeywordRanking.Google.Rank)\t\(.KeywordRanking.Google.Url)\t\(.KeywordRanking.Yahoo.Rank)\t\(.KeywordRanking.Yahoo.Url)\t\(.KeywordStats.AdvertiserCompetition)\t\(.KeywordStats.CPC)\t\(.KeywordStats.GlobalSearchVolume)\t\(.KeywordStats.LocalSearchTrendsByMonth.Apr)\t\(.KeywordStats.LocalSearchTrendsByMonth.Aug)\t\(.KeywordStats.LocalSearchTrendsByMonth.Dec)\t\(.KeywordStats.LocalSearchTrendsByMonth.Feb)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jan)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jul)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jun)\t\(.KeywordStats.LocalSearchTrendsByMonth.Mar)\t\(.KeywordStats.LocalSearchTrendsByMonth.May)\t\(.KeywordStats.LocalSearchTrendsByMonth.Nov)\t\(.KeywordStats.LocalSearchTrendsByMonth.Oct)\t\(.KeywordStats.LocalSearchTrendsByMonth.Sep)\t\(.KeywordStats.RegionalSearchVolume)\t\(.KeywordTags)\t\(.RequestUrl)"' /home/warehouse/files/keywordList/$MYENV/keywordList20000.json >> /home/warehouse/files/csv/keywords/$MYENV/outputKeyword20000.csv  
~/jq -r '.Response.Result[] | "\(.CreatedAt)\t\(.Id)\t\(.Keyword)\t\(.KeywordDevice)\t\(.KeywordLocation)\t\(.KeywordMarket)\t\(.KeywordRanking.Bing.Rank)\t\(.KeywordRanking.Bing.Url)\t\(.KeywordRanking.date)\t\(.KeywordRanking.Google.BaseRank)\t\(.KeywordRanking.Google.Rank)\t\(.KeywordRanking.Google.Url)\t\(.KeywordRanking.Yahoo.Rank)\t\(.KeywordRanking.Yahoo.Url)\t\(.KeywordStats.AdvertiserCompetition)\t\(.KeywordStats.CPC)\t\(.KeywordStats.GlobalSearchVolume)\t\(.KeywordStats.LocalSearchTrendsByMonth.Apr)\t\(.KeywordStats.LocalSearchTrendsByMonth.Aug)\t\(.KeywordStats.LocalSearchTrendsByMonth.Dec)\t\(.KeywordStats.LocalSearchTrendsByMonth.Feb)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jan)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jul)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jun)\t\(.KeywordStats.LocalSearchTrendsByMonth.Mar)\t\(.KeywordStats.LocalSearchTrendsByMonth.May)\t\(.KeywordStats.LocalSearchTrendsByMonth.Nov)\t\(.KeywordStats.LocalSearchTrendsByMonth.Oct)\t\(.KeywordStats.LocalSearchTrendsByMonth.Sep)\t\(.KeywordStats.RegionalSearchVolume)\t\(.KeywordTags)\t\(.RequestUrl)"' /home/warehouse/files/keywordList/$MYENV/keywordList25000.json >> /home/warehouse/files/csv/keywords/$MYENV/outputKeyword25000.csv 
~/jq -r '.Response.Result[] | "\(.CreatedAt)\t\(.Id)\t\(.Keyword)\t\(.KeywordDevice)\t\(.KeywordLocation)\t\(.KeywordMarket)\t\(.KeywordRanking.Bing.Rank)\t\(.KeywordRanking.Bing.Url)\t\(.KeywordRanking.date)\t\(.KeywordRanking.Google.BaseRank)\t\(.KeywordRanking.Google.Rank)\t\(.KeywordRanking.Google.Url)\t\(.KeywordRanking.Yahoo.Rank)\t\(.KeywordRanking.Yahoo.Url)\t\(.KeywordStats.AdvertiserCompetition)\t\(.KeywordStats.CPC)\t\(.KeywordStats.GlobalSearchVolume)\t\(.KeywordStats.LocalSearchTrendsByMonth.Apr)\t\(.KeywordStats.LocalSearchTrendsByMonth.Aug)\t\(.KeywordStats.LocalSearchTrendsByMonth.Dec)\t\(.KeywordStats.LocalSearchTrendsByMonth.Feb)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jan)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jul)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jun)\t\(.KeywordStats.LocalSearchTrendsByMonth.Mar)\t\(.KeywordStats.LocalSearchTrendsByMonth.May)\t\(.KeywordStats.LocalSearchTrendsByMonth.Nov)\t\(.KeywordStats.LocalSearchTrendsByMonth.Oct)\t\(.KeywordStats.LocalSearchTrendsByMonth.Sep)\t\(.KeywordStats.RegionalSearchVolume)\t\(.KeywordTags)\t\(.RequestUrl)"' /home/warehouse/files/keywordList/$MYENV/keywordList30000.json >> /home/warehouse/files/csv/keywords/$MYENV/outputKeyword30000.csv
~/jq -r '.Response.Result[] | "\(.CreatedAt)\t\(.Id)\t\(.Keyword)\t\(.KeywordDevice)\t\(.KeywordLocation)\t\(.KeywordMarket)\t\(.KeywordRanking.Bing.Rank)\t\(.KeywordRanking.Bing.Url)\t\(.KeywordRanking.date)\t\(.KeywordRanking.Google.BaseRank)\t\(.KeywordRanking.Google.Rank)\t\(.KeywordRanking.Google.Url)\t\(.KeywordRanking.Yahoo.Rank)\t\(.KeywordRanking.Yahoo.Url)\t\(.KeywordStats.AdvertiserCompetition)\t\(.KeywordStats.CPC)\t\(.KeywordStats.GlobalSearchVolume)\t\(.KeywordStats.LocalSearchTrendsByMonth.Apr)\t\(.KeywordStats.LocalSearchTrendsByMonth.Aug)\t\(.KeywordStats.LocalSearchTrendsByMonth.Dec)\t\(.KeywordStats.LocalSearchTrendsByMonth.Feb)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jan)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jul)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jun)\t\(.KeywordStats.LocalSearchTrendsByMonth.Mar)\t\(.KeywordStats.LocalSearchTrendsByMonth.May)\t\(.KeywordStats.LocalSearchTrendsByMonth.Nov)\t\(.KeywordStats.LocalSearchTrendsByMonth.Oct)\t\(.KeywordStats.LocalSearchTrendsByMonth.Sep)\t\(.KeywordStats.RegionalSearchVolume)\t\(.KeywordTags)\t\(.RequestUrl)"' /home/warehouse/files/keywordList/$MYENV/keywordList35000.json >> /home/warehouse/files/csv/keywords/$MYENV/outputKeyword35000.csv 
~/jq -r '.Response.Result[] | "\(.CreatedAt)\t\(.Id)\t\(.Keyword)\t\(.KeywordDevice)\t\(.KeywordLocation)\t\(.KeywordMarket)\t\(.KeywordRanking.Bing.Rank)\t\(.KeywordRanking.Bing.Url)\t\(.KeywordRanking.date)\t\(.KeywordRanking.Google.BaseRank)\t\(.KeywordRanking.Google.Rank)\t\(.KeywordRanking.Google.Url)\t\(.KeywordRanking.Yahoo.Rank)\t\(.KeywordRanking.Yahoo.Url)\t\(.KeywordStats.AdvertiserCompetition)\t\(.KeywordStats.CPC)\t\(.KeywordStats.GlobalSearchVolume)\t\(.KeywordStats.LocalSearchTrendsByMonth.Apr)\t\(.KeywordStats.LocalSearchTrendsByMonth.Aug)\t\(.KeywordStats.LocalSearchTrendsByMonth.Dec)\t\(.KeywordStats.LocalSearchTrendsByMonth.Feb)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jan)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jul)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jun)\t\(.KeywordStats.LocalSearchTrendsByMonth.Mar)\t\(.KeywordStats.LocalSearchTrendsByMonth.May)\t\(.KeywordStats.LocalSearchTrendsByMonth.Nov)\t\(.KeywordStats.LocalSearchTrendsByMonth.Oct)\t\(.KeywordStats.LocalSearchTrendsByMonth.Sep)\t\(.KeywordStats.RegionalSearchVolume)\t\(.KeywordTags)\t\(.RequestUrl)"' /home/warehouse/files/keywordList/$MYENV/keywordList40000.json >> /home/warehouse/files/csv/keywords/$MYENV/outputKeyword40000.csv
~/jq -r '.Response.Result[] | "\(.CreatedAt)\t\(.Id)\t\(.Keyword)\t\(.KeywordDevice)\t\(.KeywordLocation)\t\(.KeywordMarket)\t\(.KeywordRanking.Bing.Rank)\t\(.KeywordRanking.Bing.Url)\t\(.KeywordRanking.date)\t\(.KeywordRanking.Google.BaseRank)\t\(.KeywordRanking.Google.Rank)\t\(.KeywordRanking.Google.Url)\t\(.KeywordRanking.Yahoo.Rank)\t\(.KeywordRanking.Yahoo.Url)\t\(.KeywordStats.AdvertiserCompetition)\t\(.KeywordStats.CPC)\t\(.KeywordStats.GlobalSearchVolume)\t\(.KeywordStats.LocalSearchTrendsByMonth.Apr)\t\(.KeywordStats.LocalSearchTrendsByMonth.Aug)\t\(.KeywordStats.LocalSearchTrendsByMonth.Dec)\t\(.KeywordStats.LocalSearchTrendsByMonth.Feb)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jan)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jul)\t\(.KeywordStats.LocalSearchTrendsByMonth.Jun)\t\(.KeywordStats.LocalSearchTrendsByMonth.Mar)\t\(.KeywordStats.LocalSearchTrendsByMonth.May)\t\(.KeywordStats.LocalSearchTrendsByMonth.Nov)\t\(.KeywordStats.LocalSearchTrendsByMonth.Oct)\t\(.KeywordStats.LocalSearchTrendsByMonth.Sep)\t\(.KeywordStats.RegionalSearchVolume)\t\(.KeywordTags)\t\(.RequestUrl)"' /home/warehouse/files/keywordList/$MYENV/keywordList45000.json >> /home/warehouse/files/csv/keywords/$MYENV/outputKeyword45000.csv

#number=`date -d "$todate -1 days" "+%Y%m%d"`
#cd /home/warehouse/files/csv/keywords/$MYENV
#for f in *; 
#do   /usr/bin/az dls fs upload --account rentpathdatalake --source-path $f --destination-path /PROD/API-STAT/Keywords/$f --overwrite; 
#done

cd /home/warehouse/files/csv/keywords/$MYENV
ls -l
number=$((`date +%Y%m%d -d "1 day ago"`))
for f in *; 
do   /usr/bin/az dls fs upload --account rentpathdatalake --source-path $f --destination-path /$MYENV/Output/STAT/Keywords/brand=aptg/$f --overwrite; 
done

if [ $? -ne 0 -o `grep ERROR $LOGFILE | wc -l` -gt 0 ]
then
    cat $LOGFILE >&2
    echo "`date` `basename $0` FAILED..." >&2
    rm -f $LOGFILE $LOCKFILE 2>/dev/null
       exit 1
fi

echo "`date` `basename $0` $1 SUCCESS..."
rm -f $LOCKFILE $LOGFILE 2>/dev/null
exit 0

